automating analytics
pixlee/pixlee-ios-sdk pull request #35
Opened 2021-01-27 09:12 UTC by SungjunApp

ticket: https://pixlee.atlassian.net/browse/EN-3568

# Supported automatic Analytics events

## API
### PXLAlbum
- Loadmore: This is always automatic meaning if you receive 2...N pages, this event will always be fired. PXLAlbum class will handle this event. you no longer need to fire this manually anymore.

## UI components
UI components now have an option of firing analytics events automatically. 

### PXLGridView (similar to Widget)
- VisibleWidget
- OpenedWidget

###  PXLPhotoProductView (similar to Lightbox)
- OpenLightbox

# How to enable it?
###  PXLGridView
```swift
#!swift
var gridView = PXLGridView()
// alternative: pxlGridView.enableAutoAnalytics(album: album, widgetType: "custom widget name")
pxlGridView.enableAutoAnalytics(album: album, widgetType: PXLWidgetType.photowall)
```
###  PXLPhotoProductView
```swift
#!swift
let widget = PXLPhotoProductView.widgetForPhoto(photo: photo, delegate: self)
let regionId: Int? = nil
widget.enableAutoAnalytics(regionId: regionId)
pxlPhotoProductView.setContent(...)
...
```

# UI Tests are added
- This is to monitor whether analytics events are successfully fired on UI elements.
- UI tests run on Circle CI. 

### How the tests work for analytics (Similar to how the Android SDK's testing works)
1. The tests mimic user behaviors by clicking and swiping views on the UI Components to fire an account's real analytics. 
2. Succeeded and failed analytics events will be broadcasted within the app via NotificationCenter. 
3. Then, tests can listen to capture the notification events to make sure that they are fired.
4. If everything works fine on all steps above, the tests passed.

2021-01-27 16:42 UTC, jchen123 approved these changes
this is so awesome. my question is for current users who may or may not be firing their events manually, if they upgraded to this, then their analytics should not change at all right?  its only when they manually toggle it to be automatic, then remove their manual event firing, then it will be automatic?  it would be bad if they upgraded and then started seeing double events

2021-01-27 16:45 UTC, jchen123 commented on Classes/SDK/Widgets/PXLGridView.swift
> +    func fireAnalytics() {
i think this shoul be a better name than just fireAnalytics. even if it were more verbose like fireOpenAndVisible

2021-01-27 16:45 UTC, jchen123 commented on Classes/SDK/Widgets/PXLGridView.swift
> +            fireAnalytics()
does this fire without checking for a boolean for automatic analytics on or off?

2021-01-28 00:39 UTC, SungjunApp commented
@jchen123 to use this feature, they have to explicitly enable the auto-analytics feature on each UI component by using <view>.enableAutoAnalytics(...) except `loadmore`.

'loadmore' has become to be always on so can have double events based on this structure. I'll change this to be off by default and add an argument to turn it on.

2021-01-28 00:49 UTC, SungjunApp commented on Classes/SDK/Widgets/PXLGridView.swift
> +            fireAnalytics()
There are codes to check this.

they are enabled via <instance of PXLGridView>.enableAutoAnalytics(album: PXLAlbum, widgetType: String). If both album: PXLAlbum and widgetType: String are not nil (not null), they are activated. 

They are varified in fireAnalytics() -> [fireAnalyticsOpenedWidget() / fireAnalyticsWidgetVisible()].

2021-01-28 16:00 UTC, jchen123 requested changes
switching to "request changes" given our discussion for this and Android

2021-01-29 17:12 UTC, jchen123 approved these changes
it all looks right. i'd feel comfortable if we manually tested that events dont get fired when auto analytics is off, but seems good

2021-01-29 17:12 UTC, jchen123 commented on Classes/SDK/Widgets/PXLGridView.swift
> +            print("autoAnalyticsDelegate or PXLGridViewDelegate.setupAlbumForAutoAnalytics(){..} is not spcified")
specified spelling

2021-01-29 17:12 UTC, jchen123 commented on Classes/SDK/Widgets/PXLGridView.swift
> +            print("You need to spcify 'class YourViewController PXLGridViewDelegate.setupAlbumForAutoAnalytics(){return (yourAlbum, your widget type)}'")
specify spelling

2021-02-01 02:39 UTC, merged

2021-02-01 03:09 UTC, SungjunApp commented
I manually tested analytics by turning it off and on, testing the views, and iterating it. also added a UI test to verify this. All look fine.